#!/usr/sbin/nft -f

destroy table inet firewall

table inet firewall {
        chain input {
                type filter hook input priority filter; policy drop;
                iif "lo" accept
                ct state { established, related } accept
                meta nfproto vmap { ipv4 : jump input_ipv4, ipv6 : jump input_ipv6 }
                ct state invalid drop
                tcp dport { 80, 443, 40022 } accept
                udp dport 443 accept
        }

        chain input_ipv4 {
                icmp type { destination-unreachable, time-exceeded, parameter-problem } limit rate 100/second burst 100 packets accept
                icmp type echo-request limit rate 30/second burst 50 packets accept
        }

        chain input_ipv6 {
                icmpv6 type { nd-router-solicit, nd-router-advert, nd-neighbor-solicit, nd-neighbor-advert } ip6 hoplimit 255 accept
                icmpv6 type { destination-unreachable, packet-too-big, time-exceeded, parameter-problem } limit rate 100/second burst 100 packets accept
                icmpv6 type echo-request limit rate 30/second burst 50 packets accept
        }

        chain forward {
                type filter hook forward priority filter; policy drop;
        }

        chain output {
                type filter hook output priority filter; policy accept;
        }
}