flush ruleset

table inet firewall {
    chain input {
        type filter hook input priority 0; policy drop;
        # 允许回环接口
        iif lo accept
        # 状态检查
        ct state invalid drop
        ct state { established, related } accept
        # 反欺骗检查
        fib saddr . iif oif missing drop
        # 允许特定 TCP/UDP 端口
        tcp dport { 80, 443, 30022 } accept
        udp dport 443 accept
        # ICMP 处理
        meta protocol vmap { ip : jump input_ipv4, ip6 : jump input_ipv6 }
    }

    chain input_ipv4 {
        # 允许 Ping
        icmp type echo-request limit rate 5/second burst 10 packets accept
        # 允许路径 MTU 发现
        icmp type { destination-unreachable, time-exceeded, parameter-problem } accept
    }

    chain input_ipv6 {
        # 允许 Ping
        icmpv6 type echo-request limit rate 5/second burst 10 packets accept
        # 允许 IPv6 邻居发现
        icmpv6 type { nd-neighbor-solicit, nd-neighbor-advert, nd-router-advert } ip6 hoplimit 255 accept
        # 允许路径 MTU 发现
        icmpv6 type { packet-too-big, destination-unreachable, time-exceeded, parameter-problem } accept
    }

    chain forward {
        type filter hook forward priority 0; policy drop;
    }

    chain output {
        type filter hook output priority 0; policy accept;
    }
}